apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: app-svc
  endpoints:
  - interval: 30s
    targetPort: 5000
    path: /metrics
    