apiVersion: v1
kind: Pod
metadata:
  name: app-service
  namespace: monitoring
  labels:
    app: app-service
spec:
  containers:
  - name: app-service
    # image: avilakathara/remla24-group7-app:0.0.1
    image: proksch/showmetrics:latest # test using in-class example
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-service-serv
  namespace: monitoring
  labels:
    app: app-service-serv
spec:
  type: NodePort
  selector:
    app: app-service
  ports:
  - name: app-service
    port: 8080
    targetPort: 3000 # try
    nodePort: 30040 # try
    # port: 30040
    # targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: app-service-serv
  endpoints:
  - port: app-service
    interval: 120s
    