apiVersion: v1
kind: Pod
metadata:
  name: app-service
  labels:
    app: app-service
spec:
  containers:
  - name: app-service
    image: avilakathara/remla24-group7-app:latest 
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-service-serv
  labels:
    app: app-service-serv
spec:
  type: NodePort
  selector:
    app: app-service
  ports:
  - port: 30040
    targetPort: 5000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service-monitor
  labels:
    release: myprom
spec:
  selector:
    matchLabels:
      app: app-service-serv
  endpoints:
  - interval: 1s