name: phishing-detection-cnn

services:
  model-service:
    image: ghcr.io/remla24-team7/model-service:0.1.1
    volumes:
      - ./model:/app/model

  app:
    image: ghcr.io/remla24-team7/app:0.1.0
    environment:
      - MODEL_SERVICE_URL=http://model-service:5000
    ports:
      - 5000:5000
    depends_on:
      - model-service
