name: phishing-detection-cnn

services:
  model-service:
    image: model-service
    build: ../model-service
    volumes:
      - ./model:/app/model

  app:
    image: app-service
    build: ../app
    environment:
      - MODEL_SERVICE_URL=http://model-service:5000
    ports:
      - 5000:5000
    depends_on:
      - model-service
