- hosts: all
  become: true
  tasks:
    - name: Update apt repos/cache
      apt:
        update_cache: true

- hosts: controller
  become: true
  tasks:
    - name: Install k3s server
      shell: curl -sfL https://get.k3s.io | sh -
      environment:
        INSTALL_K3S_EXEC: "--node-ip={{ node_ip }} --node-external-ip={{ node_ip }}"
        K3S_KUBECONFIG_MODE: 644

    - name: Install Helm
      shell: |
        curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
        apt-get install apt-transport-https --yes
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        apt-get update
        apt-get install helm

    - name: Install Prometheus
      shell: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        helm install prometheus prometheus-community/kube-prometheus-stack --create-namespace --namespace monitoring
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Share kubeconfig (k3s.yaml)
      copy:
        remote_src: true
        src: /etc/rancher/k3s/k3s.yaml
        dest: /vagrant/k3s.yaml

    - name: Update server endpoint to private_network in kubeconfig
      replace:
        path: /vagrant/k3s.yaml
        regexp: "127.0.0.1"
        replace: "{{ node_ip }}"

    - name: Share k3s node token
      copy:
        remote_src: true
        src: /var/lib/rancher/k3s/server/node-token
        dest: /vagrant/k3s-node-token

- hosts: node
  become: true
  tasks:
    - name: Get shared k3s node token
      slurp:
        src: /vagrant/k3s-node-token
      register: k3s_token

    - name: Install k3s agent
      shell: curl -sfL https://get.k3s.io | sh -
      environment:
        INSTALL_K3S_EXEC: "--node-ip={{ node_ip }} --node-external-ip={{ node_ip }}"
        K3S_URL: "https://{{ controller_ip }}:6443"
        K3S_TOKEN: "{{ k3s_token.content | b64decode | trim }}"